import type { CheapSharkStore, Deal } from './types';

/**
 * Resilience fallback — used only when the live CheapShark API is
 * unreachable so the UI always renders a coherent experience.
 * These are illustrative records shaped exactly like the live payload.
 */
export const FALLBACK_STORES: CheapSharkStore[] = [
  {
    storeID: '1',
    storeName: 'Steam',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/0.png',
      logo: '/img/stores/logos/0.png',
      icon: '/img/stores/icons/0.png',
    },
  },
  {
    storeID: '7',
    storeName: 'GOG',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/7.png',
      logo: '/img/stores/logos/7.png',
      icon: '/img/stores/icons/7.png',
    },
  },
  {
    storeID: '11',
    storeName: 'Humble',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/11.png',
      logo: '/img/stores/logos/11.png',
      icon: '/img/stores/icons/11.png',
    },
  },
  {
    storeID: '25',
    storeName: 'Epic',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/25.png',
      logo: '/img/stores/logos/25.png',
      icon: '/img/stores/icons/25.png',
    },
  },
  {
    storeID: '8',
    storeName: 'EA Origin',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/8.png',
      logo: '/img/stores/logos/8.png',
      icon: '/img/stores/icons/8.png',
    },
  },
  {
    storeID: '13',
    storeName: 'Utomik',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/13.png',
      logo: '/img/stores/logos/13.png',
      icon: '/img/stores/icons/13.png',
    },
  },
  {
    storeID: '15',
    storeName: 'Fanatical',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/15.png',
      logo: '/img/stores/logos/15.png',
      icon: '/img/stores/icons/15.png',
    },
  },
  {
    storeID: '31',
    storeName: 'Blizzard',
    isActive: 1,
    images: {
      banner: '/img/stores/banners/31.png',
      logo: '/img/stores/logos/31.png',
      icon: '/img/stores/icons/31.png',
    },
  },
];

const now = Math.floor(Date.now() / 1000);

export const FALLBACK_DEALS: Deal[] = [
  {
    internalName: 'ELDENRING',
    title: 'ELDEN RING',
    metacriticLink: '/game/pc/elden-ring.html',
    dealID: 'fallback-elden-ring',
    storeID: '1',
    gameID: '224552',
    steamAppID: '1245620',
    salePrice: '29.99',
    normalPrice: '59.99',
    isOnSale: '1',
    savings: '50.00',
    metacriticScore: '94',
    steamRatingPercent: '92',
    steamRatingText: 'Very Positive',
    steamRatingCount: '243453',
    releaseDate: 1645670400,
    lastChange: now,
    dealRating: '9.0',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
  },
  {
    internalName: 'REDDEADREDEMPTION2',
    title: 'Red Dead Redemption 2',
    metacriticLink: '/game/pc/red-dead-redemption-2.html',
    dealID: 'fallback-rdr2',
    storeID: '7',
    gameID: '178023',
    steamAppID: '1174180',
    salePrice: '14.99',
    normalPrice: '59.99',
    isOnSale: '1',
    savings: '75.00',
    metacriticScore: '93',
    steamRatingPercent: '89',
    steamRatingText: 'Very Positive',
    steamRatingCount: '198742',
    releaseDate: 1572566400,
    lastChange: now,
    dealRating: '9.5',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg',
  },
  {
    internalName: 'CYBERPUNK2077',
    title: 'Cyberpunk 2077',
    metacriticLink: '/game/pc/cyberpunk-2077.html',
    dealID: 'fallback-cyberpunk',
    storeID: '11',
    gameID: '172131',
    steamAppID: '1091500',
    salePrice: '29.99',
    normalPrice: '59.99',
    isOnSale: '1',
    savings: '50.00',
    metacriticScore: '86',
    steamRatingPercent: '81',
    steamRatingText: 'Very Positive',
    steamRatingCount: '542118',
    releaseDate: 1608595200,
    lastChange: now,
    dealRating: '8.7',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
  },
  {
    internalName: 'HALF-LIFE2',
    title: 'Half-Life 2',
    metacriticLink: '/game/pc/half-life-2.html',
    dealID: 'fallback-hl2',
    storeID: '1',
    gameID: '612',
    steamAppID: '220',
    salePrice: '2.99',
    normalPrice: '9.99',
    isOnSale: '1',
    savings: '70.02',
    metacriticScore: '96',
    steamRatingPercent: '97',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '98211',
    releaseDate: 1100035200,
    lastChange: now,
    dealRating: '9.3',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/220/header.jpg',
  },
  {
    internalName: 'STARDERWVALLEY',
    title: 'Stardew Valley',
    metacriticLink: '/game/pc/stardew-valley.html',
    dealID: 'fallback-stardew',
    storeID: '15',
    gameID: '91553',
    steamAppID: '413150',
    salePrice: '9.99',
    normalPrice: '14.99',
    isOnSale: '1',
    savings: '33.36',
    metacriticScore: '89',
    steamRatingPercent: '98',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '412983',
    releaseDate: 1456704000,
    lastChange: now,
    dealRating: '9.4',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
  },
  {
    internalName: 'HOLLOWKNIGHT',
    title: 'Hollow Knight',
    metacriticLink: '/game/pc/hollow-knight.html',
    dealID: 'fallback-hollow',
    storeID: '7',
    gameID: '73821',
    steamAppID: '367520',
    salePrice: '7.49',
    normalPrice: '14.99',
    isOnSale: '1',
    savings: '50.03',
    metacriticScore: '90',
    steamRatingPercent: '97',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '201234',
    releaseDate: 1490745600,
    lastChange: now,
    dealRating: '9.2',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
  },
  {
    internalName: 'HadesII',
    title: 'Hades II',
    metacriticLink: '',
    dealID: 'fallback-hades2',
    storeID: '1',
    gameID: '210198',
    steamAppID: '1145350',
    salePrice: '24.99',
    normalPrice: '29.99',
    isOnSale: '1',
    savings: '16.67',
    metacriticScore: '0',
    steamRatingPercent: '95',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '67421',
    releaseDate: 1716422400,
    lastChange: now,
    dealRating: '8.9',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg',
  },
  {
    internalName: 'BaldursGate3',
    title: "Baldur's Gate 3",
    metacriticLink: '/game/pc/baldurs-gate-3.html',
    dealID: 'fallback-bg3',
    storeID: '11',
    gameID: '208914',
    steamAppID: '1086940',
    salePrice: '41.99',
    normalPrice: '59.99',
    isOnSale: '1',
    savings: '30.00',
    metacriticScore: '96',
    steamRatingPercent: '96',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '388902',
    releaseDate: 1692921600,
    lastChange: now,
    dealRating: '9.6',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',
  },
  {
    internalName: 'Dishonored',
    title: 'Dishonored',
    metacriticLink: '/game/pc/dishonored.html',
    dealID: 'fallback-dishonored',
    storeID: '25',
    gameID: '41221',
    steamAppID: '205100',
    salePrice: '0.00',
    normalPrice: '19.99',
    isOnSale: '1',
    savings: '100.00',
    metacriticScore: '91',
    steamRatingPercent: '94',
    steamRatingText: 'Very Positive',
    steamRatingCount: '24118',
    releaseDate: 1350000000,
    lastChange: now,
    dealRating: '9.1',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/205100/header.jpg',
  },
  {
    internalName: 'TheWitcher3WildHunt',
    title: 'The Witcher 3: Wild Hunt',
    metacriticLink: '/game/pc/the-witcher-3-wild-hunt.html',
    dealID: 'fallback-witcher3',
    storeID: '7',
    gameID: '32742',
    steamAppID: '292030',
    salePrice: '9.99',
    normalPrice: '39.99',
    isOnSale: '1',
    savings: '75.02',
    metacriticScore: '93',
    steamRatingPercent: '97',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '542981',
    releaseDate: 1431648000,
    lastChange: now,
    dealRating: '9.5',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
  },
  {
    internalName: 'DOOMETTERNAL',
    title: 'DOOM Eternal',
    metacriticLink: '/game/pc/doom-eternal.html',
    dealID: 'fallback-doom',
    storeID: '1',
    gameID: '167090',
    steamAppID: '782330',
    salePrice: '11.99',
    normalPrice: '39.99',
    isOnSale: '1',
    savings: '70.01',
    metacriticScore: '88',
    steamRatingPercent: '92',
    steamRatingText: 'Very Positive',
    steamRatingCount: '88421',
    releaseDate: 1584230400,
    lastChange: now,
    dealRating: '9.0',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg',
  },
  {
    internalName: 'Portal2',
    title: 'Portal 2',
    metacriticLink: '/game/pc/portal-2.html',
    dealID: 'fallback-portal2',
    storeID: '1',
    gameID: '3264',
    steamAppID: '620',
    salePrice: '1.99',
    normalPrice: '9.99',
    isOnSale: '1',
    savings: '80.08',
    metacriticScore: '95',
    steamRatingPercent: '98',
    steamRatingText: 'Overwhelmingly Positive',
    steamRatingCount: '172339',
    releaseDate: 1301616000,
    lastChange: now,
    dealRating: '9.4',
    thumb: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg',
  },
];
