packages:
  - '.'
allowBuilds:
  sharp: set this to true or false
  typesense-instantsearch-adapter: set this to true or false
onlyBuiltDependencies:
  - sharp
  - typesense-instantsearch-adapter
  - unrs-resolver
