#!/usr/bin/env bash
# scripts/affiliate-onboarding.sh
# Scaffold .env.local with placeholder entries for all affiliate networks.
# Run once. Fill in approved IDs from each network dashboard afterwards.

set -euo pipefail

ENV_FILE=".env.local"

if [ -f "$ENV_FILE" ]; then
  echo "❌ $ENV_FILE already exists. Edit manually to add affiliate IDs."
  echo "   See docs/affiliate-onboarding.md for the full guide."
  exit 1
fi

POSTBACK_SECRET=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/affiliate-onboarding.sh
# After approval, fill in each ID from the network dashboard.
# See docs/affiliate-onboarding.md for application links + postback URLs.

POSTBACK_SECRET=$POSTBACK_SECRET

# Impact (Eneba, Fanatical) — Campaign ID
AFF_ENEBA_ID=
AFF_FANATICAL_ID=

# PartnerStack (Humble, Kinguin)
AFF_HUMBLE_CHARITY=
AFF_HUMBLE_PARTNER=
AFF_KINGUIN_ID=

# In-house affiliate IDs
AFF_GAMIVO_ID=
AFF_WINGAMESTORE_ID=
AFF_GAMEBILLET_ID=
AFF_VOIDU_ID=
AFF_GAMESPLANET_ID=
AFF_INDIEGALA_ID=
AFF_DLGAMER_ID=

# CJ Affiliate (CDKeys) — Publisher ID, used as mw_aref param
AFF_CDKEYS_REF=
EOF

chmod 600 "$ENV_FILE"

echo "✅ Created $ENV_FILE (mode 600)"
echo "📋 POSTBACK_SECRET generated: $POSTBACK_SECRET"
echo ""
echo "Next steps:"
echo "1. Read docs/affiliate-onboarding.md"
echo "2. Apply to each network (Eneba + Fanatical first — fastest approval)"
echo "3. Fill in AFF_*_ID values in $ENV_FILE"
echo "4. Configure postback URL in each dashboard with the same POSTBACK_SECRET"
echo "5. Test with: curl -i 'http://localhost:3000/out/103/cyberpunk-2077'"
